In [1]:
## Read FileNames
import glob
extension = 'csv'
all_filenames = [i for i in glob.glob('nov-2019-*.{}'.format(extension))]
all_filenames

['nov-2019-s1.csv', 'nov-2019-s2.csv', 'nov-2019-s3.csv', 'nov-2019-s4.csv']

In [2]:
#read and combine all files in the PandaDataFrame
import pandas as pd
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
#combined_csv.to_csv( "combined_csv.csv", index=False, encoding='utf-8-sig')
combined_csv.head()

C:\Users\Kalairani VIGNESH\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3338: DtypeWarning: Columns (4,31,38,39) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):
C:\Users\Kalairani VIGNESH\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3338: DtypeWarning: Columns (4,31,38,39,53) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,itp,registration_number,legal_name,application,...,legal_infos_lastname,legal_infos_email,legal_infos_phone,legal_infos_head_office_branch_number,legal_infos_legal_nature_code,legal_infos_legal_nature_label,legal_infos_company_business_sector_code,legal_infos_company_business_sector_label,legal_infos_creation_date,legal_infos_update_date
0,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,117550106150,8.400588e+13,BLOCK'OUT,CBEMV,...,NaN,NaN,NaN,13.0,5710.0,"SAS, société par actions simplifiée",93.29Z,Autres activités récréatives et de loisirs,2018-05-03,NaN
1,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,117550106150,8.400588e+13,BLOCK'OUT,CBEMV,...,NaN,NaN,NaN,13.0,5710.0,"SAS, société par actions simplifiée",93.29Z,Autres activités récréatives et de loisirs,2018-05-03,NaN
2,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,117550106150,8.400588e+13,BLOCK'OUT,CBEMV,...,NaN,NaN,NaN,13.0,5710.0,"SAS, société par actions simplifiée",93.29Z,Autres activités récréatives et de loisirs,2018-05-03,NaN
3,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,117550106150,8.400588e+13,BLOCK'OUT,CBEMV,...,NaN,NaN,NaN,13.0,5710.0,"SAS, société par actions simplifiée",93.29Z,Autres activités récréatives et de loisirs,2018-05-03,NaN
4,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,117550106150,8.400588e+13,BLOCK'OUT,CBEMV,...,NaN,NaN,NaN,13.0,5710.0,"SAS, société par actions simplifiée",93.29Z,Autres activités récréatives et de loisirs,2018-05-03,NaN

In [3]:
combined_csv.shape

(7679010, 77)

In [4]:

pd.set_option('display.max_columns', None)

In [5]:
with open("Columns_to_be_removed.csv") as file_in:
    lines = []
    for line in file_in:
        lines.append(line.strip())

In [6]:
lines

['itp',
 'ert',
 'cb_version',
 'timezone',
 'reconciliation_number',
 'reconciliation_code',
 'pos_remittance_number',
 'transfer_code',
 'authorization_code',
 'aid',
 'terminal_verification_results',
 'rfut_code',
 'rfut_label',
 'message_to_initiator',
 'error_fields',
 'field_conversions',
 'payment_facilitator',
 'application_selection_indicator',
 'selected_brand',
 'audit_number',
 'transaction_number',
 'legal_infos_uuid',
 'legal_infos_branch_number',
 'legal_infos_normalized_address_l1',
 'legal_infos_normalized_address_l2',
 'legal_infos_normalized_address_l3',
 'legal_infos_normalized_address_l4',
 'legal_infos_normalized_address_l5',
 'legal_infos_normalized_address_l6',
 'legal_infos_business_postal_code',
 'legal_infos_is_head_office',
 'legal_infos_business_name',
 'legal_infos_branch_business_sector_code',
 'legal_infos_branch_business_sector_label',
 'legal_infos_civility',
 'legal_infos_forname',
 'legal_infos_lastname',
 'legal_infos_email',
 'legal_infos_phone',
 'legal_infos_head_office_branch_number',
 'legal_infos_legal_nature_code',
 'legal_infos_legal_nature_label',
 'legal_infos_company_business_sector_code',
 'legal_infos_company_business_sector_label',
 'legal_infos_creation_date',
 'legal_infos_update_date']

In [7]:
combined_csv=combined_csv.drop(lines,axis=1)

In [8]:
combined_csv.shape

(7679010, 31)

In [9]:
#Exporting the combined file
combined_csv.to_csv( "combined_csv.csv", index=False, encoding='utf-8-sig')

In [9]:
combined_csv.columns

Index(['created_at', 'serial_number', 'manufacturer', 'contract_number',
       'contract_rank', 'bank_code', 'registration_number', 'legal_name',
       'application', 'currency_code', 'mcc', 'local_transaction_datetime',
       'credits_number', 'debits_number', 'debits_reversal_number',
       'non_completed_number', 'credits_amount', 'debits_amount',
       'debits_reversal_amount', 'transaction_count',
       'local_transaction_datetime.1', 'amount', 'authorization_number',
       'type', 'legal_infos_registration_number',
       'legal_infos_head_office_registration_number',
       'legal_infos_normalized_address_l7', 'legal_infos_postal_code',
       'legal_infos_city_name', 'legal_infos_company_long_name',
       'legal_infos_acronym'],
      dtype='object')

In [10]:
#Number of merchants, different SIREN Number
combined_csv.legal_infos_head_office_registration_number.nunique()

11831

In [11]:
#Number of unique pos teriminals
combined_csv.serial_number.nunique()

19028

In [12]:
#Records with no SIREN 
combined_csv.legal_infos_head_office_registration_number.isna().value_counts()

False    6783164
True      895846
Name: legal_infos_head_office_registration_number, dtype: int64

In [13]:
#Taking data with Null SIREN

In [16]:
combined_csv.drop_duplicates(["legal_infos_head_office_registration_number","local_transaction_datetime","serial_number"]).to_csv( "SirenSerialAndTransactionTimeGroup.csv", index=False, encoding='utf-8-sig')

In [17]:
combined_csv.shape

(7679010, 31)

In [21]:
### Data Transformation - Fill the SIREN
#Step 1 - find Serial Number Siren Mapping
combined_csv["legal_infos_head_office_registration_number"].dtype

combined_csv["legal_infos_head_office_registration_number"] = combined_csv["legal_infos_head_office_registration_number"].astype(str)

In [22]:
SerialNumberAndSIREN =combined_csv.groupby('serial_number')['legal_infos_head_office_registration_number'].agg([('legal_infos_head_office_registration_number', '| '.join)]).reset_index()
SerialNumberAndSIREN

      serial_number        legal_infos_head_office_registration_number
0      00081925B168  490202033.0| 490202033.0| 490202033.0| 4902020...
1      0008192665D7  399410265.0| 399410265.0| 399410265.0| 3994102...
2      000819277F8D  843442807.0| 843442807.0| 843442807.0| 8434428...
3      00081927802D                            nan| nan| nan| nan| nan
4      0008192781E3  843442807.0| 843442807.0| 843442807.0| 8434428...
...             ...                                                ...
19023    WL84636245  nan| nan| nan| nan| nan| nan| nan| nan| nan| n...
19024    WL84636260  nan| nan| nan| nan| nan| nan| nan| nan| nan| n...
19025    WL84636297  304961212.0| 304961212.0| 304961212.0| 3049612...
19026    WL84636332  479823031.0| 479823031.0| 479823031.0| 4798230...
19027    WL84636344  nan| nan| nan| nan| nan| nan| nan| nan| nan| n...

[19028 rows x 2 columns]

In [23]:
def remove_dup(string):
    temp=string.split('|')
    temp=[x.strip() for x in temp]
    return '|'.join(set(temp))


def hasNaNinSIREN(string):
    if "nan" in string:
        return True
    else:
        return False

def hasOnlyNan(string):
    if "nan" in string and "|" not in string:
        return True
    else:
        return False

def hasMoreThanOneSIRENExcludingNan(string):
    temp=string.split('|')
    if "nan" in temp:
        temp.remove("nan")
    if len(temp) > 1:
        return True
    else:
        return False



SerialNumberAndSIREN["uniqueSIRENNumber"] = SerialNumberAndSIREN['legal_infos_head_office_registration_number'].apply(remove_dup)
SerialNumberAndSIREN["hasNaN"] = SerialNumberAndSIREN['legal_infos_head_office_registration_number'].apply(hasNaNinSIREN)
SerialNumberAndSIREN["hasOnlyNaN"] = SerialNumberAndSIREN['uniqueSIRENNumber'].apply(hasOnlyNan)

SerialNumberAndSIREN["hasMoreThanOneSIRENExcludingNan"] = SerialNumberAndSIREN['uniqueSIRENNumber'].apply(hasMoreThanOneSIRENExcludingNan)

In [24]:
SerialNumberAndSIREN=SerialNumberAndSIREN.drop(["legal_infos_head_office_registration_number"], axis=1)

In [25]:
SerialNumberAndSIREN

,serial_number,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan
0,00081925B168,490202033.0,False,False,False
1,0008192665D7,399410265.0,False,False,False
2,000819277F8D,843442807.0,False,False,False
3,00081927802D,nan,True,True,False
4,0008192781E3,843442807.0,False,False,False
...,...,...,...,...,...
19023,WL84636245,nan,True,True,False
19024,WL84636260,nan,True,True,False
19025,WL84636297,304961212.0,False,False,False
19026,WL84636332,479823031.0,False,False,False
19027,WL84636344,nan,True,True,False

In [26]:
def isDiscard(record):
    if(record[0]):
        return True
    if(record[1] and record[2]):
        return True
    else:
        return False

SerialNumberAndSIREN["ToDiscard"] = SerialNumberAndSIREN[["hasOnlyNaN","hasNaN","hasMoreThanOneSIRENExcludingNan"]].apply(isDiscard,axis=1)

In [117]:
SerialNumberAndSIREN.to_csv( "SerialNumberAndSIREN.csv", index=False, encoding='utf-8-sig')

In [27]:
combined_csv_Discard = pd.merge(combined_csv,SerialNumberAndSIREN, left_on="serial_number", right_on="serial_number")

In [28]:
combined_csv_Discard.shape

(7679010, 36)

In [31]:
combined_csv_Discard[(combined_csv_Discard["legal_infos_head_office_registration_number"] == "nan") & (combined_csv_Discard["hasOnlyNaN"])]

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard
17516,2019-11-09 01:25:06.647969+00,CT01832012,SAGEM,5258214,1,10207,8.514169e+13,NaN,CBEMV,978,5811,2019-11-09 02:25:00,0,8,0,0,0.0,201.31,0.0,8,2019-11-08 13:25:53,34.96,NaN,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,True,True,False,True
17517,2019-11-09 01:25:06.647969+00,CT01832012,SAGEM,5258214,1,10207,8.514169e+13,NaN,CBEMV,978,5811,2019-11-09 02:25:00,0,8,0,0,0.0,201.31,0.0,8,2019-11-08 19:18:16,8.76,NaN,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,True,True,False,True
17518,2019-11-09 01:25:06.647969+00,CT01832012,SAGEM,5258214,1,10207,8.514169e+13,NaN,CBEMV,978,5811,2019-11-09 02:25:00,0,8,0,0,0.0,201.31,0.0,8,2019-11-08 18:32:20,26.49,NaN,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,True,True,False,True
17519,2019-11-09 01:25:06.647969+00,CT01832012,SAGEM,5258214,1,10207,8.514169e+13,NaN,CBEMV,978,5811,2019-11-09 02:25:00,0,8,0,0,0.0,201.31,0.0,8,2019-11-08 17:06:57,7.86,NaN,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,True,True,False,True
17520,2019-11-09 01:25:06.647969+00,CT01832012,SAGEM,5258214,1,10207,8.514169e+13,NaN,CBEMV,978,5811,2019-11-09 02:25:00,0,8,0,0,0.0,201.31,0.0,8,2019-11-08 16:41:38,34.08,NaN,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7678947,2019-11-30 19:25:10.961348+00,WL80840001,SAGEM,5944377,2,16607,8.486705e+13,NaN,CBEMV,978,5200,2019-11-30 20:24:41,0,32,0,0,0.0,2035.00,0.0,32,2019-11-30 14:42:18,45.00,198549,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,True,True,False,True
7678948,2019-11-30 19:25:10.961348+00,WL80840001,SAGEM,5944377,2,16607,8.486705e+13,NaN,CBEMV,978,5200,2019-11-30 20:24:41,0,32,0,0,0.0,2035.00,0.0,32,2019-11-30 14:36:08,90.00,055326,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,True,True,False,True
7678949,2019-11-30 19:25:10.961348+00,WL80840001,SAGEM,5944377,2,16607,8.486705e+13,NaN,CBEMV,978,5200,2019-11-30 20:24:41,0,32,0,0,0.0,2035.00,0.0,32,2019-11-30 14:28:29,25.00,NaN,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,True,True,False,True
7678950,2019-11-30 19:25:10.961348+00,WL80840001,SAGEM,5944377,2,16607,8.486705e+13,NaN,CBEMV,978,5200,2019-11-30 20:24:41,0,32,0,0,0.0,2035.00,0.0,32,2019-11-30 14:08:05,45.00,NaN,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,True,True,False,True
7678951,2019-11-30 19:25:10.961348+00,WL80840001,SAGEM,5944377,2,16607,8.486705e+13,NaN,CBEMV,978,5200,2019-11-30 20:24:41,0,32,0,0,0.0,2035.00,0.0,32,2019-11-30 12:56:37,70.00,NaN,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,True,True,False,True

In [32]:
combined_csv_Discard[(combined_csv_Discard["legal_infos_head_office_registration_number"] == "nan") & (combined_csv_Discard["hasNaN"]) & (combined_csv_Discard["hasMoreThanOneSIRENExcludingNan"])]

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard
75662,2019-11-07 19:43:07.597525+00,WL81174574,SAGEM,4756042,1,30004,5.008593e+12,NaN,CBEMV,978,8021,2019-11-07 20:42:52,0,5,0,0,0.0,750.56,0.0,5,2019-11-07 09:48:24,114.42,375421,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,333076529.0|393109046.0|379145717.0|nan,True,False,True,True
75663,2019-11-07 19:43:07.597525+00,WL81174574,SAGEM,4756042,1,30004,5.008593e+12,NaN,CBEMV,978,8021,2019-11-07 20:42:52,0,5,0,0,0.0,750.56,0.0,5,2019-11-07 11:43:38,43.38,NaN,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,333076529.0|393109046.0|379145717.0|nan,True,False,True,True
75664,2019-11-07 19:43:07.597525+00,WL81174574,SAGEM,4756042,1,30004,5.008593e+12,NaN,CBEMV,978,8021,2019-11-07 20:42:52,0,5,0,0,0.0,750.56,0.0,5,2019-11-07 11:02:11,403.00,134981,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,333076529.0|393109046.0|379145717.0|nan,True,False,True,True
75665,2019-11-07 19:43:07.597525+00,WL81174574,SAGEM,4756042,1,30004,5.008593e+12,NaN,CBEMV,978,8021,2019-11-07 20:42:52,0,5,0,0,0.0,750.56,0.0,5,2019-11-07 10:15:18,43.38,NaN,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,333076529.0|393109046.0|379145717.0|nan,True,False,True,True
75666,2019-11-07 19:43:07.597525+00,WL81174574,SAGEM,4756042,1,30004,5.008593e+12,NaN,CBEMV,978,8021,2019-11-07 20:42:52,0,5,0,0,0.0,750.56,0.0,5,2019-11-07 11:46:18,146.38,959115,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,333076529.0|393109046.0|379145717.0|nan,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7650377,2019-11-30 01:45:02.28988+00,WL83965606,SAGEM,9492957311,6,0,8.222328e+13,NaN,AMEX,978,0,2019-11-30 02:44:53,0,4,0,0,0.0,4836.00,0.0,4,2019-11-30 01:39:40,61.00,894158,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,822232799.0|432122505.0|nan,True,False,True,True
7650378,2019-11-30 01:45:02.28988+00,WL83965606,SAGEM,9492957311,6,0,8.222328e+13,NaN,AMEX,978,0,2019-11-30 02:44:53,0,4,0,0,0.0,4836.00,0.0,4,2019-11-30 02:08:23,3100.00,252912,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,822232799.0|432122505.0|nan,True,False,True,True
7663196,2019-11-30 03:38:27.062862+00,WL83223741,SAGEM,9492566823,013,0,8.016443e+13,NaN,AMEX,978,0,2019-11-30 04:38:16,0,3,0,0,0.0,280.00,0.0,3,2019-11-30 02:43:04,40.00,843820,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,432122505.0|801644295.0|nan,True,False,True,True
7663197,2019-11-30 03:38:27.062862+00,WL83223741,SAGEM,9492566823,013,0,8.016443e+13,NaN,AMEX,978,0,2019-11-30 04:38:16,0,3,0,0,0.0,280.00,0.0,3,2019-11-30 02:39:28,120.00,807841,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,432122505.0|801644295.0|nan,True,False,True,True
7663198,2019-11-30 03:38:27.062862+00,WL83223741,SAGEM,9492566823,013,0,8.016443e+13,NaN,AMEX,978,0,2019-11-30 04:38:16,0,3,0,0,0.0,280.00,0.0,3,2019-11-30 02:40:01,120.00,881290,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,432122505.0|801644295.0|nan,True,False,True,True

In [33]:
combined_csv_Discard[(combined_csv_Discard["legal_infos_head_office_registration_number"] == "nan") & (combined_csv_Discard["hasNaN"]) & (combined_csv_Discard["hasMoreThanOneSIRENExcludingNan"] == False)]

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard
4462,2019-11-09 00:39:40.293005+00,WL03244629,SAGEM,9490026218,001,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-09 01:39:25,0,2,0,0,0.0,82.0,0.0,2,2019-11-08 17:34:16,77.0,871218,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False
4463,2019-11-09 00:39:40.293005+00,WL03244629,SAGEM,9490026218,001,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-09 01:39:25,0,2,0,0,0.0,82.0,0.0,2,2019-11-08 14:27:11,5.0,802469,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False
4474,2019-11-09 23:27:03.887772+00,WL03244629,SAGEM,9490026218,1,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-10 00:27:01,0,1,0,0,0.0,35.8,0.0,1,2019-11-09 14:14:50,35.8,880123,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False
4482,2019-11-08 00:05:24.779311+00,WL03244629,SAGEM,9490026218,1,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-08 01:05:18,0,3,0,0,0.0,116.6,0.0,3,2019-11-07 14:01:36,43.6,809263,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False
4483,2019-11-08 00:05:24.779311+00,WL03244629,SAGEM,9490026218,1,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-08 01:05:18,0,3,0,0,0.0,116.6,0.0,3,2019-11-07 21:20:59,39.0,806199,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7678947,2019-11-30 19:25:10.961348+00,WL80840001,SAGEM,5944377,2,16607,8.486705e+13,NaN,CBEMV,978,5200,2019-11-30 20:24:41,0,32,0,0,0.0,2035.0,0.0,32,2019-11-30 14:42:18,45.0,198549,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,True,True,False,True
7678948,2019-11-30 19:25:10.961348+00,WL80840001,SAGEM,5944377,2,16607,8.486705e+13,NaN,CBEMV,978,5200,2019-11-30 20:24:41,0,32,0,0,0.0,2035.0,0.0,32,2019-11-30 14:36:08,90.0,055326,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,True,True,False,True
7678949,2019-11-30 19:25:10.961348+00,WL80840001,SAGEM,5944377,2,16607,8.486705e+13,NaN,CBEMV,978,5200,2019-11-30 20:24:41,0,32,0,0,0.0,2035.0,0.0,32,2019-11-30 14:28:29,25.0,NaN,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,True,True,False,True
7678950,2019-11-30 19:25:10.961348+00,WL80840001,SAGEM,5944377,2,16607,8.486705e+13,NaN,CBEMV,978,5200,2019-11-30 20:24:41,0,32,0,0,0.0,2035.0,0.0,32,2019-11-30 14:08:05,45.0,NaN,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,True,True,False,True
7678951,2019-11-30 19:25:10.961348+00,WL80840001,SAGEM,5944377,2,16607,8.486705e+13,NaN,CBEMV,978,5200,2019-11-30 20:24:41,0,32,0,0,0.0,2035.0,0.0,32,2019-11-30 12:56:37,70.0,NaN,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,nan,True,True,False,True

In [34]:
combined_csv_Discard[(combined_csv_Discard["legal_infos_head_office_registration_number"] == "nan") & (combined_csv_Discard["hasNaN"]) & (combined_csv_Discard["hasMoreThanOneSIRENExcludingNan"] == False) & (combined_csv_Discard["hasOnlyNaN"] == False)]

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard
4462,2019-11-09 00:39:40.293005+00,WL03244629,SAGEM,9490026218,001,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-09 01:39:25,0,2,0,0,0.0,82.0,0.0,2,2019-11-08 17:34:16,77.0,871218,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False
4463,2019-11-09 00:39:40.293005+00,WL03244629,SAGEM,9490026218,001,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-09 01:39:25,0,2,0,0,0.0,82.0,0.0,2,2019-11-08 14:27:11,5.0,802469,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False
4474,2019-11-09 23:27:03.887772+00,WL03244629,SAGEM,9490026218,1,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-10 00:27:01,0,1,0,0,0.0,35.8,0.0,1,2019-11-09 14:14:50,35.8,880123,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False
4482,2019-11-08 00:05:24.779311+00,WL03244629,SAGEM,9490026218,1,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-08 01:05:18,0,3,0,0,0.0,116.6,0.0,3,2019-11-07 14:01:36,43.6,809263,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False
4483,2019-11-08 00:05:24.779311+00,WL03244629,SAGEM,9490026218,1,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-08 01:05:18,0,3,0,0,0.0,116.6,0.0,3,2019-11-07 21:20:59,39.0,806199,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7677271,2019-11-26 18:29:50.673657+00,WL80103150,SAGEM,1999400,1,17806,8.888000e+13,NaN,CBEMV,978,8999,2019-11-26 19:29:44,0,0,0,1,0.0,0.0,0.0,1,2019-11-26 19:29:12,1.0,NaN,TNA,NaN,nan,NaN,NaN,NaN,NaN,NaN,489779231.0|nan,True,False,False,False
7677291,2019-11-25 15:08:40.328528+00,WL80068238,SAGEM,1999400,1,17806,8.888000e+13,NaN,CBEMV,978,8999,2019-11-25 16:08:35,0,1,0,0,0.0,1.0,0.0,1,2019-11-25 16:08:11,1.0,6674,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,831962675.0|nan,True,False,False,False
7677773,2019-11-30 01:46:29.365007+00,WL80733649,SAGEM,9491072237,1,0,9.491072e+09,NaN,AMEX,978,0,2019-11-30 02:46:21,0,1,0,0,0.0,16.0,0.0,1,2019-11-30 00:19:45,16.0,887048,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,502436017.0|nan,True,False,False,False
7677987,2019-11-29 22:21:55.598009+00,WL11350173,SAGEM,9495628596,1,0,9.495629e+09,NaN,NaN,978,0,2019-11-29 23:21:44,0,1,0,0,0.0,98.0,0.0,1,2019-11-29 18:45:55,98.0,847908,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,331843151.0|nan,True,False,False,False
7678008,2019-11-30 22:21:41.963613+00,WL11350173,SAGEM,9495628596,1,0,9.495629e+09,NaN,NaN,978,0,2019-11-30 23:21:30,0,1,0,0,0.0,81.0,0.0,1,2019-11-30 10:51:26,81.0,888831,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,331843151.0|nan,True,False,False,False

In [35]:
combined_csv_Discard[(combined_csv_Discard["legal_infos_head_office_registration_number"] == "nan") & (combined_csv_Discard["hasNaN"]) & (combined_csv_Discard["hasMoreThanOneSIRENExcludingNan"] == False) & (combined_csv_Discard["hasOnlyNaN"] == False)].serial_number.nunique()

2472

In [32]:
combined_csv_Discard.drop_duplicates(["legal_infos_head_office_registration_number","mcc"]).to_csv( "SirenAndMCC.csv", index=False, encoding='utf-8-sig')

In [158]:
combined_csv_Discard[combined_csv_Discard.serial_number == "285210631"]

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard
7620998,2019-11-19 08:02:45.710342+00,285210631,VERIFONE,2058865,1,30002,4.918412e+13,TAYO LIBRAIRIE DES VOYAGEURS ET DES - GEOMATICART,CBCLESS,978,2741,2019-11-19 09:02:00,0,1,0,1,0.0,1.11,0.0,2,2019-11-16 15:05:35,111.00,NaN,TNA,4.918412e+13,491841243.0,FRANCE,4100.0,MANOSQUE,TAYO LIBRAIRIE DES VOYAGEURS ET DES,NaN,491841243.0|nan,True,False,False,False
7620999,2019-11-19 08:02:45.710342+00,285210631,VERIFONE,2058865,1,30002,4.918412e+13,TAYO LIBRAIRIE DES VOYAGEURS ET DES - GEOMATICART,CBCLESS,978,2741,2019-11-19 09:02:00,0,1,0,1,0.0,1.11,0.0,2,2019-11-16 15:04:50,1.11,NaN,DEBIT,4.918412e+13,491841243.0,FRANCE,4100.0,MANOSQUE,TAYO LIBRAIRIE DES VOYAGEURS ET DES,NaN,491841243.0|nan,True,False,False,False
7621000,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-29 11:24:58,60.00,NaN,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False
7621001,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-19 10:39:58,119.00,654255,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False
7621002,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-16 15:06:24,111.00,NaN,TNA,NaN,nan,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False
7621003,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-16 10:28:28,43.00,NaN,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False
7621004,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-12 10:40:11,238.00,544863,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False
7621005,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-07 16:18:31,75.00,043348,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False
7621006,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-02 14:46:58,265.00,156555,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False
7621007,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-02 12:28:27,39.00,474753,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False
7621008,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-30 15:28:25,14.00,NaN,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False
7621009,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-29 12:27:25,153.00,255167,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False
7621010,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-29 12:25:25,153.00,122616,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False
7621011,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-26 17:22:51,146.00,324753,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False

In [36]:

SirenMapping = pd.read_csv("SirenToUpdateMapping.csv")

In [37]:
SirenMapping["UpdatedSIRENNumber"] = SirenMapping["UpdatedSIRENNumber"].astype(str)
SirenMapping.dtypes

serial_number         object
UpdatedSIRENNumber    object
dtype: object

In [38]:
combined_csv_Siren_Filled = pd.merge(combined_csv_Discard,SirenMapping,how="left")

In [39]:
combined_csv_Siren_Filled.shape

(7679010, 37)

In [40]:
combined_csv_Siren_Filled.dtypes

created_at                                      object
serial_number                                   object
manufacturer                                    object
contract_number                                  int64
contract_rank                                   object
bank_code                                        int64
registration_number                            float64
legal_name                                      object
application                                     object
currency_code                                    int64
mcc                                              int64
local_transaction_datetime                      object
credits_number                                   int64
debits_number                                    int64
debits_reversal_number                           int64
non_completed_number                             int64
credits_amount                                 float64
debits_amount                                  float64
debits_reversal_amount                         float64
transaction_count                                int64
local_transaction_datetime.1                    object
amount                                         float64
authorization_number                            object
type                                            object
legal_infos_registration_number                float64
legal_infos_head_office_registration_number     object
legal_infos_normalized_address_l7               object
legal_infos_postal_code                        float64
legal_infos_city_name                           object
legal_infos_company_long_name                   object
legal_infos_acronym                             object
uniqueSIRENNumber                               object
hasNaN                                            bool
hasOnlyNaN                                        bool
hasMoreThanOneSIRENExcludingNan                   bool
ToDiscard                                         bool
UpdatedSIRENNumber                              object
dtype: object

In [45]:
combined_csv_Siren_Filled["UpdatedSIRENNumber"] = combined_csv_Siren_Filled["UpdatedSIRENNumber"].astype(str)

In [46]:
combined_csv_Siren_Filled

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard,UpdatedSIRENNumber
0,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 20:19:02,7.50,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
1,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 13:13:51,25.40,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
2,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 14:54:32,44.80,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
3,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 17:15:16,46.40,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
4,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 21:41:02,35.40,334335,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7679005,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-18 00:17:26,126.55,NaN,TNA,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan
7679006,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-18 00:17:52,126.55,183956,DEBIT,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan
7679007,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-18 00:18:39,126.57,192778,DEBIT,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan
7679008,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-28 22:27:12,56.00,NaN,TNA,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan
7679009,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-28 21:29:43,15.00,NaN,DEBIT,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan

In [47]:
combined_csv_Siren_Filled[(combined_csv_Siren_Filled["legal_infos_head_office_registration_number"] == "nan") & (combined_csv_Siren_Filled["hasNaN"]) & (combined_csv_Siren_Filled["hasMoreThanOneSIRENExcludingNan"] == False) & (combined_csv_Siren_Filled["hasOnlyNaN"] == False)].serial_number.nunique()

2472

In [48]:
combined_csv_Siren_Filled[(combined_csv_Siren_Filled["legal_infos_head_office_registration_number"] == "nan") & (combined_csv_Siren_Filled["UpdatedSIRENNumber"] != "nan")]

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard,UpdatedSIRENNumber
4462,2019-11-09 00:39:40.293005+00,WL03244629,SAGEM,9490026218,001,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-09 01:39:25,0,2,0,0,0.0,82.0,0.0,2,2019-11-08 17:34:16,77.0,871218,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False,751929357
4463,2019-11-09 00:39:40.293005+00,WL03244629,SAGEM,9490026218,001,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-09 01:39:25,0,2,0,0,0.0,82.0,0.0,2,2019-11-08 14:27:11,5.0,802469,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False,751929357
4474,2019-11-09 23:27:03.887772+00,WL03244629,SAGEM,9490026218,1,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-10 00:27:01,0,1,0,0,0.0,35.8,0.0,1,2019-11-09 14:14:50,35.8,880123,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False,751929357
4482,2019-11-08 00:05:24.779311+00,WL03244629,SAGEM,9490026218,1,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-08 01:05:18,0,3,0,0,0.0,116.6,0.0,3,2019-11-07 14:01:36,43.6,809263,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False,751929357
4483,2019-11-08 00:05:24.779311+00,WL03244629,SAGEM,9490026218,1,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-08 01:05:18,0,3,0,0,0.0,116.6,0.0,3,2019-11-07 21:20:59,39.0,806199,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False,751929357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7677271,2019-11-26 18:29:50.673657+00,WL80103150,SAGEM,1999400,1,17806,8.888000e+13,NaN,CBEMV,978,8999,2019-11-26 19:29:44,0,0,0,1,0.0,0.0,0.0,1,2019-11-26 19:29:12,1.0,NaN,TNA,NaN,nan,NaN,NaN,NaN,NaN,NaN,489779231.0|nan,True,False,False,False,489779231
7677291,2019-11-25 15:08:40.328528+00,WL80068238,SAGEM,1999400,1,17806,8.888000e+13,NaN,CBEMV,978,8999,2019-11-25 16:08:35,0,1,0,0,0.0,1.0,0.0,1,2019-11-25 16:08:11,1.0,6674,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,831962675.0|nan,True,False,False,False,831962675
7677773,2019-11-30 01:46:29.365007+00,WL80733649,SAGEM,9491072237,1,0,9.491072e+09,NaN,AMEX,978,0,2019-11-30 02:46:21,0,1,0,0,0.0,16.0,0.0,1,2019-11-30 00:19:45,16.0,887048,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,502436017.0|nan,True,False,False,False,502436017
7677987,2019-11-29 22:21:55.598009+00,WL11350173,SAGEM,9495628596,1,0,9.495629e+09,NaN,NaN,978,0,2019-11-29 23:21:44,0,1,0,0,0.0,98.0,0.0,1,2019-11-29 18:45:55,98.0,847908,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,331843151.0|nan,True,False,False,False,331843151
7678008,2019-11-30 22:21:41.963613+00,WL11350173,SAGEM,9495628596,1,0,9.495629e+09,NaN,NaN,978,0,2019-11-30 23:21:30,0,1,0,0,0.0,81.0,0.0,1,2019-11-30 10:51:26,81.0,888831,DEBIT,NaN,nan,NaN,NaN,NaN,NaN,NaN,331843151.0|nan,True,False,False,False,331843151

In [50]:
import numpy as np
combined_csv_Siren_Filled['legal_infos_head_office_registration_number'] = np.where( (combined_csv_Siren_Filled['legal_infos_head_office_registration_number'] == 'nan') & (combined_csv_Siren_Filled['UpdatedSIRENNumber'] != 'nan'), combined_csv_Siren_Filled['UpdatedSIRENNumber'] , combined_csv_Siren_Filled['legal_infos_head_office_registration_number'])

In [51]:
combined_csv_Siren_Filled[combined_csv_Siren_Filled.legal_infos_head_office_registration_number!="nan"]

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard,UpdatedSIRENNumber
0,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 20:19:02,7.50,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
1,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 13:13:51,25.40,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
2,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 14:54:32,44.80,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
3,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 17:15:16,46.40,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
4,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 21:41:02,35.40,334335,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7679005,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-18 00:17:26,126.55,NaN,TNA,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan
7679006,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-18 00:17:52,126.55,183956,DEBIT,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan
7679007,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-18 00:18:39,126.57,192778,DEBIT,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan
7679008,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-28 22:27:12,56.00,NaN,TNA,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan
7679009,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-28 21:29:43,15.00,NaN,DEBIT,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan

In [54]:
combined_csv.legal_infos_head_office_registration_number.nunique()

11832

In [49]:
combined_csv_Siren_Filled[(combined_csv_Siren_Filled.legal_infos_head_office_registration_number.notna()) & (combined_csv_Siren_Filled["ToDiscard"] == False)]

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard,UpdatedSIRENNumber
0,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 20:19:02,7.50,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,NaN
1,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 13:13:51,25.40,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,NaN
2,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 14:54:32,44.80,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,NaN
3,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 17:15:16,46.40,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,NaN
4,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 21:41:02,35.40,334335,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7679005,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-18 00:17:26,126.55,NaN,TNA,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,NaN
7679006,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-18 00:17:52,126.55,183956,DEBIT,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,NaN
7679007,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-18 00:18:39,126.57,192778,DEBIT,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,NaN
7679008,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-28 22:27:12,56.00,NaN,TNA,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,NaN
7679009,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-28 21:29:43,15.00,NaN,DEBIT,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,NaN

In [56]:
combined_csv_Siren_Filled[(combined_csv_Siren_Filled["legal_infos_head_office_registration_number"] != "nan")]

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard,UpdatedSIRENNumber
0,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 20:19:02,7.50,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
1,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 13:13:51,25.40,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
2,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 14:54:32,44.80,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
3,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 17:15:16,46.40,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
4,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 21:41:02,35.40,334335,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7679005,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-18 00:17:26,126.55,NaN,TNA,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan
7679006,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-18 00:17:52,126.55,183956,DEBIT,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan
7679007,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-18 00:18:39,126.57,192778,DEBIT,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan
7679008,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-28 22:27:12,56.00,NaN,TNA,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan
7679009,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-28 21:29:43,15.00,NaN,DEBIT,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan

In [57]:
combined_csv_Siren_Cleaned = combined_csv_Siren_Filled[(combined_csv_Siren_Filled["legal_infos_head_office_registration_number"] != "nan")]

In [58]:
combined_csv_Siren_Cleaned[combined_csv_Siren_Cleaned['legal_infos_head_office_registration_number'] != 'nan']

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard,UpdatedSIRENNumber
0,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 20:19:02,7.50,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
1,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 13:13:51,25.40,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
2,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 14:54:32,44.80,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
3,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 17:15:16,46.40,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
4,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 21:41:02,35.40,334335,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7679005,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-18 00:17:26,126.55,NaN,TNA,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan
7679006,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-18 00:17:52,126.55,183956,DEBIT,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan
7679007,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-18 00:18:39,126.57,192778,DEBIT,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan
7679008,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-28 22:27:12,56.00,NaN,TNA,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan
7679009,2019-11-29 13:58:31.059717+00,PT62550094,SAGEM,8708726,1,13825,7.527916e+13,CARRE ROYAL - CARRE ROYAL,CBEMV,978,5812,2019-11-29 14:56:00,0,32,0,24,0.0,2564.54,0.0,56,2019-11-28 21:29:43,15.00,NaN,DEBIT,7.527916e+13,752791582.0,FRANCE,69001.0,LYON 1ER,CARRE ROYAL,NaN,752791582.0,False,False,False,False,nan

In [59]:
combined_csv_Siren_Cleaned.serial_number.nunique()

16539

In [60]:
combined_csv_Siren_Cleaned.to_csv("combined_csv_Siren_Cleaned_Version2.csv", index=False, encoding='utf-8-sig')

In [61]:
combined_csv_Siren_Cleaned.shape

(6921286, 37)

In [62]:
combined_csv_Siren_Cleaned.legal_infos_head_office_registration_number.nunique()

13273

In [64]:
combined_csv_Siren_Cleaned[combined_csv_Siren_Cleaned.serial_number == "285210631"]

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard,UpdatedSIRENNumber
7620998,2019-11-19 08:02:45.710342+00,285210631,VERIFONE,2058865,1,30002,4.918412e+13,TAYO LIBRAIRIE DES VOYAGEURS ET DES - GEOMATICART,CBCLESS,978,2741,2019-11-19 09:02:00,0,1,0,1,0.0,1.11,0.0,2,2019-11-16 15:05:35,111.00,NaN,TNA,4.918412e+13,491841243.0,FRANCE,4100.0,MANOSQUE,TAYO LIBRAIRIE DES VOYAGEURS ET DES,NaN,491841243.0|nan,True,False,False,False,491841243
7620999,2019-11-19 08:02:45.710342+00,285210631,VERIFONE,2058865,1,30002,4.918412e+13,TAYO LIBRAIRIE DES VOYAGEURS ET DES - GEOMATICART,CBCLESS,978,2741,2019-11-19 09:02:00,0,1,0,1,0.0,1.11,0.0,2,2019-11-16 15:04:50,1.11,NaN,DEBIT,4.918412e+13,491841243.0,FRANCE,4100.0,MANOSQUE,TAYO LIBRAIRIE DES VOYAGEURS ET DES,NaN,491841243.0|nan,True,False,False,False,491841243
7621000,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-29 11:24:58,60.00,NaN,DEBIT,NaN,491841243,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621001,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-19 10:39:58,119.00,654255,DEBIT,NaN,491841243,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621002,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-16 15:06:24,111.00,NaN,TNA,NaN,491841243,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621003,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-16 10:28:28,43.00,NaN,DEBIT,NaN,491841243,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621004,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-12 10:40:11,238.00,544863,DEBIT,NaN,491841243,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621005,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-07 16:18:31,75.00,043348,DEBIT,NaN,491841243,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621006,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-02 14:46:58,265.00,156555,DEBIT,NaN,491841243,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621007,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-02 12:28:27,39.00,474753,DEBIT,NaN,491841243,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621008,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-30 15:28:25,14.00,NaN,DEBIT,NaN,491841243,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621009,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-29 12:27:25,153.00,255167,DEBIT,NaN,491841243,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621010,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-29 12:25:25,153.00,122616,DEBIT,NaN,491841243,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621011,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-26 17:22:51,146.00,324753,DEBIT,NaN,491841243,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243

In [66]:
combined_csv_Siren_Cleaned["legal_infos_head_office_registration_number"] = combined_csv_Siren_Cleaned["legal_infos_head_office_registration_number"].astype(float)

<ipython-input-66-84862f36f193>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_csv_Siren_Cleaned["legal_infos_head_office_registration_number"] = combined_csv_Siren_Cleaned["legal_infos_head_office_registration_number"].astype(float)

In [67]:
combined_csv_Siren_Cleaned[combined_csv_Siren_Cleaned.serial_number == "285210631"]

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard,UpdatedSIRENNumber
7620998,2019-11-19 08:02:45.710342+00,285210631,VERIFONE,2058865,1,30002,4.918412e+13,TAYO LIBRAIRIE DES VOYAGEURS ET DES - GEOMATICART,CBCLESS,978,2741,2019-11-19 09:02:00,0,1,0,1,0.0,1.11,0.0,2,2019-11-16 15:05:35,111.00,NaN,TNA,4.918412e+13,491841243.0,FRANCE,4100.0,MANOSQUE,TAYO LIBRAIRIE DES VOYAGEURS ET DES,NaN,491841243.0|nan,True,False,False,False,491841243
7620999,2019-11-19 08:02:45.710342+00,285210631,VERIFONE,2058865,1,30002,4.918412e+13,TAYO LIBRAIRIE DES VOYAGEURS ET DES - GEOMATICART,CBCLESS,978,2741,2019-11-19 09:02:00,0,1,0,1,0.0,1.11,0.0,2,2019-11-16 15:04:50,1.11,NaN,DEBIT,4.918412e+13,491841243.0,FRANCE,4100.0,MANOSQUE,TAYO LIBRAIRIE DES VOYAGEURS ET DES,NaN,491841243.0|nan,True,False,False,False,491841243
7621000,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-29 11:24:58,60.00,NaN,DEBIT,NaN,491841243.0,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621001,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-19 10:39:58,119.00,654255,DEBIT,NaN,491841243.0,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621002,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-16 15:06:24,111.00,NaN,TNA,NaN,491841243.0,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621003,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-16 10:28:28,43.00,NaN,DEBIT,NaN,491841243.0,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621004,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-12 10:40:11,238.00,544863,DEBIT,NaN,491841243.0,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621005,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-07 16:18:31,75.00,043348,DEBIT,NaN,491841243.0,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621006,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-02 14:46:58,265.00,156555,DEBIT,NaN,491841243.0,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621007,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-02 12:28:27,39.00,474753,DEBIT,NaN,491841243.0,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621008,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-30 15:28:25,14.00,NaN,DEBIT,NaN,491841243.0,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621009,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-29 12:27:25,153.00,255167,DEBIT,NaN,491841243.0,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621010,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-29 12:25:25,153.00,122616,DEBIT,NaN,491841243.0,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243
7621011,2019-11-30 14:31:12.959079+00,285210631,VERIFONE,3969803,1,30003,5.009470e+12,NaN,CBEMV,978,5651,2019-11-30 15:29:22,0,11,0,1,0.0,1305.00,0.0,12,2019-11-26 17:22:51,146.00,324753,DEBIT,NaN,491841243.0,NaN,NaN,NaN,NaN,NaN,491841243.0|nan,True,False,False,False,491841243

In [68]:
combined_csv_Siren_Cleaned.to_csv("combined_csv_Siren_Cleaned_Version2.csv", index=False, encoding='utf-8-sig')

In [69]:
combined_csv_Siren_Cleaned.loc[combined_csv_Siren_Cleaned["legal_infos_head_office_registration_number"] == "285210631"]

Empty DataFrame
Columns: [created_at, serial_number, manufacturer, contract_number, contract_rank, bank_code, registration_number, legal_name, application, currency_code, mcc, local_transaction_datetime, credits_number, debits_number, debits_reversal_number, non_completed_number, credits_amount, debits_amount, debits_reversal_amount, transaction_count, local_transaction_datetime.1, amount, authorization_number, type, legal_infos_registration_number, legal_infos_head_office_registration_number, legal_infos_normalized_address_l7, legal_infos_postal_code, legal_infos_city_name, legal_infos_company_long_name, legal_infos_acronym, uniqueSIRENNumber, hasNaN, hasOnlyNaN, hasMoreThanOneSIRENExcludingNan, ToDiscard, UpdatedSIRENNumber]
Index: []

In [70]:
#Mapping MCC 
MCC_df=pd.read_csv("C:/Kalairani/SecondSemester/Preludd/mcc-codes-main/mcc_codes.csv")

In [71]:
MCC_df

,mcc,edited_description,combined_description,usda_description,irs_description,irs_reportable
0,742,Veterinary Services,Veterinary Services,Veterinary Services,Veterinary Services,Yes
1,763,Agricultural Co-operatives,Agricultural Co-operatives,Agricultural Co-operatives,Agricultural Cooperative,Yes
2,780,"Horticultural Services, Landscaping Services","Horticultural Services, Landscaping Services",Horticultural Services,Landscaping Services,Yes
3,1520,General Contractors-Residential and Commercial,General Contractors-Residential and Commercial,General Contractors-Residential and Commercial,General Contractors,Yes
4,1711,Air Conditioning Contractors – Sales and Insta...,Air Conditioning Contractors – Sales and Insta...,Air Conditioning Contractors – Sales and Insta...,"Heating, Plumbing, A/C",Yes
...,...,...,...,...,...,...
976,9405,Intra – Government Transactions,Intra – Government Transactions,Intra – Government Transactions,U.S. Federal Government Agencies or Departments,No1.6041-3(p)(3)
977,9700,Automated Referral Service ( For Visa Only),Automated Referral Service ( For Visa Only),Automated Referral Service ( For Visa Only),NaN,NaN
978,9701,Visa Credential Service ( For Visa Only),Visa Credential Service ( For Visa Only),Visa Credential Service ( For Visa Only),NaN,NaN
979,9702,GCAS Emergency Services ( For Visa Only),GCAS Emergency Services ( For Visa Only),GCAS Emergency Services ( For Visa Only),NaN,NaN
980,9950,Intra – Company Purchases ( For Visa Only),Intra – Company Purchases ( For Visa Only),Intra – Company Purchases ( For Visa Only),Intra-Company Purchases,No1.6041-3(c)

In [73]:
MCC_df['mcc'].nunique()

981

In [74]:
combined_csv_Siren_Cleaned.mcc.nunique()

189

In [79]:
mcc_mapped = pd.merge(combined_csv_Siren_Cleaned,MCC_df, on="mcc")

In [76]:
mcc_mapped.shape

(6870911, 42)

In [78]:

combined_csv_Siren_Cleaned.shape

(6921286, 37)

In [80]:
mcc_mapped.head()

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard,UpdatedSIRENNumber,edited_description,combined_description,usda_description,irs_description,irs_reportable
0,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 20:19:02,7.5,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Yes
1,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 13:13:51,25.4,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Yes
2,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 14:54:32,44.8,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Yes
3,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 17:15:16,46.4,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Yes
4,2019-11-07 05:06:31.00202+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBEMV,978,7991,2019-11-07 06:06:19,0,22,0,2,0.0,451.45,0.0,24,2019-11-06 21:41:02,35.4,334335,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Yes

In [86]:
combined_csv_Siren_Cleaned[combined_csv_Siren_Cleaned["mcc"] == 0]

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard,UpdatedSIRENNumber
4462,2019-11-09 00:39:40.293005+00,WL03244629,SAGEM,9490026218,001,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-09 01:39:25,0,2,0,0,0.0,82.0,0.0,2,2019-11-08 17:34:16,77.0,871218,DEBIT,NaN,751929357.0,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False,751929357
4463,2019-11-09 00:39:40.293005+00,WL03244629,SAGEM,9490026218,001,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-09 01:39:25,0,2,0,0,0.0,82.0,0.0,2,2019-11-08 14:27:11,5.0,802469,DEBIT,NaN,751929357.0,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False,751929357
4474,2019-11-09 23:27:03.887772+00,WL03244629,SAGEM,9490026218,1,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-10 00:27:01,0,1,0,0,0.0,35.8,0.0,1,2019-11-09 14:14:50,35.8,880123,DEBIT,NaN,751929357.0,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False,751929357
4482,2019-11-08 00:05:24.779311+00,WL03244629,SAGEM,9490026218,1,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-08 01:05:18,0,3,0,0,0.0,116.6,0.0,3,2019-11-07 14:01:36,43.6,809263,DEBIT,NaN,751929357.0,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False,751929357
4483,2019-11-08 00:05:24.779311+00,WL03244629,SAGEM,9490026218,1,0,7.519294e+13,GRAN CAFFE,NaN,978,0,2019-11-08 01:05:18,0,3,0,0,0.0,116.6,0.0,3,2019-11-07 21:20:59,39.0,806199,DEBIT,NaN,751929357.0,NaN,NaN,NaN,NaN,NaN,751929357.0|nan,True,False,False,False,751929357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7676188,2019-11-30 22:53:39.2604+00,CT04629508,SAGEM,9497788851,1,0,9.497789e+09,NaN,NaN,978,0,2019-11-30 23:53:29,0,3,0,0,0.0,922.0,0.0,3,2019-11-30 19:39:17,391.0,860563,DEBIT,NaN,420178550.0,NaN,NaN,NaN,NaN,NaN,420178550.0|nan,True,False,False,False,420178550
7676210,2019-11-30 01:39:47.175564+00,WL07385864,SAGEM,9492926258,0,0,9.492926e+09,NaN,NaN,978,0,2019-11-30 02:39:37,0,1,0,0,0.0,61.0,0.0,1,2019-11-29 13:54:12,61.0,839532,DEBIT,NaN,478988850.0,NaN,NaN,NaN,NaN,NaN,478988850.0|nan,True,False,False,False,478988850
7677773,2019-11-30 01:46:29.365007+00,WL80733649,SAGEM,9491072237,1,0,9.491072e+09,NaN,AMEX,978,0,2019-11-30 02:46:21,0,1,0,0,0.0,16.0,0.0,1,2019-11-30 00:19:45,16.0,887048,DEBIT,NaN,502436017.0,NaN,NaN,NaN,NaN,NaN,502436017.0|nan,True,False,False,False,502436017
7677987,2019-11-29 22:21:55.598009+00,WL11350173,SAGEM,9495628596,1,0,9.495629e+09,NaN,NaN,978,0,2019-11-29 23:21:44,0,1,0,0,0.0,98.0,0.0,1,2019-11-29 18:45:55,98.0,847908,DEBIT,NaN,331843151.0,NaN,NaN,NaN,NaN,NaN,331843151.0|nan,True,False,False,False,331843151
7678008,2019-11-30 22:21:41.963613+00,WL11350173,SAGEM,9495628596,1,0,9.495629e+09,NaN,NaN,978,0,2019-11-30 23:21:30,0,1,0,0,0.0,81.0,0.0,1,2019-11-30 10:51:26,81.0,888831,DEBIT,NaN,331843151.0,NaN,NaN,NaN,NaN,NaN,331843151.0|nan,True,False,False,False,331843151

In [87]:
combined_csv_Siren_Cleaned[combined_csv_Siren_Cleaned["mcc"] == 9999]

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard,UpdatedSIRENNumber
588569,2019-11-09 20:34:03.370768+00,WL83320585,SAGEM,2578268,801,12869,3.982980e+13,RACINE CAREE,NaN,978,9999,2019-11-09 20:55:54,0,2,0,0,0.0,151.5,0.0,2,2019-11-09 12:09:28,39.6,900074,DEBIT,3.982980e+13,398297952.0,FRANCE,84130.0,LE PONTET,RACINE CAREE,NaN,398297952.0,False,False,False,False,nan
588570,2019-11-09 20:34:03.370768+00,WL83320585,SAGEM,2578268,801,12869,3.982980e+13,RACINE CAREE,NaN,978,9999,2019-11-09 20:55:54,0,2,0,0,0.0,151.5,0.0,2,2019-11-09 11:11:57,111.9,996636,DEBIT,3.982980e+13,398297952.0,FRANCE,84130.0,LE PONTET,RACINE CAREE,NaN,398297952.0,False,False,False,False,nan
588577,2019-11-07 20:33:36.035324+00,WL83320585,SAGEM,2578268,801,12869,3.982980e+13,RACINE CAREE,NaN,978,9999,2019-11-07 20:55:35,0,1,0,0,0.0,34.2,0.0,1,2019-11-07 10:09:54,34.2,720088,DEBIT,3.982980e+13,398297952.0,FRANCE,84130.0,LE PONTET,RACINE CAREE,NaN,398297952.0,False,False,False,False,nan
588746,2019-11-06 20:32:57.856623+00,WL83320585,SAGEM,2578268,801,12869,3.982980e+13,RACINE CAREE,NaN,978,9999,2019-11-06 20:55:02,0,2,0,0,0.0,57.6,0.0,2,2019-11-06 12:47:17,34.2,643134,DEBIT,3.982980e+13,398297952.0,FRANCE,84130.0,LE PONTET,RACINE CAREE,NaN,398297952.0,False,False,False,False,nan
588747,2019-11-06 20:32:57.856623+00,WL83320585,SAGEM,2578268,801,12869,3.982980e+13,RACINE CAREE,NaN,978,9999,2019-11-06 20:55:02,0,2,0,0,0.0,57.6,0.0,2,2019-11-06 10:45:44,23.4,635838,DEBIT,3.982980e+13,398297952.0,FRANCE,84130.0,LE PONTET,RACINE CAREE,NaN,398297952.0,False,False,False,False,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6913907,2019-11-29 16:54:46.383479+00,CT80225826,SAGEM,5758310,801,12869,3.815407e+13,A D MAROQUINIERS,NaN,978,9999,2019-11-29 20:45:08,0,5,0,0,0.0,395.6,0.0,5,2019-11-29 13:47:24,163.2,921463,DEBIT,3.815407e+13,381540681.0,FRANCE,84130.0,LE PONTET,A D MAROQUINIERS,NaN,nan|381540681.0,True,False,False,False,381540681
6913908,2019-11-29 16:54:46.383479+00,CT80225826,SAGEM,5758310,801,12869,3.815407e+13,A D MAROQUINIERS,NaN,978,9999,2019-11-29 20:45:08,0,5,0,0,0.0,395.6,0.0,5,2019-11-29 19:57:56,52.0,943690,DEBIT,3.815407e+13,381540681.0,FRANCE,84130.0,LE PONTET,A D MAROQUINIERS,NaN,nan|381540681.0,True,False,False,False,381540681
6913909,2019-11-26 16:56:19.280566+00,CT80225826,SAGEM,5758310,801,12869,3.815407e+13,A D MAROQUINIERS,NaN,978,9999,2019-11-26 20:45:29,0,1,0,2,0.0,113.2,0.0,3,2019-11-26 14:30:21,113.2,664910,DEBIT,3.815407e+13,381540681.0,FRANCE,84130.0,LE PONTET,A D MAROQUINIERS,NaN,nan|381540681.0,True,False,False,False,381540681
6913910,2019-11-26 16:56:19.280566+00,CT80225826,SAGEM,5758310,801,12869,3.815407e+13,A D MAROQUINIERS,NaN,978,9999,2019-11-26 20:45:29,0,1,0,2,0.0,113.2,0.0,3,2019-11-25 22:25:41,44.0,NaN,TNA,3.815407e+13,381540681.0,FRANCE,84130.0,LE PONTET,A D MAROQUINIERS,NaN,nan|381540681.0,True,False,False,False,381540681
6913911,2019-11-26 16:56:19.280566+00,CT80225826,SAGEM,5758310,801,12869,3.815407e+13,A D MAROQUINIERS,NaN,978,9999,2019-11-26 20:45:29,0,1,0,2,0.0,113.2,0.0,3,2019-11-25 22:27:25,44.0,NaN,TNA,3.815407e+13,381540681.0,FRANCE,84130.0,LE PONTET,A D MAROQUINIERS,NaN,nan|381540681.0,True,False,False,False,381540681

In [89]:
combined_csv_Siren_Cleaned.drop_duplicates(["legal_infos_head_office_registration_number","mcc"])[["legal_infos_head_office_registration_number","mcc"]].to_csv( "SirenAndMCC_AfterClean.csv", index=False, encoding='utf-8-sig')

In [95]:
combined_csv[combined_csv["legal_infos_head_office_registration_number"] == "343222931.0"].mcc.nunique()

4

In [96]:
combined_csv[combined_csv["legal_infos_head_office_registration_number"] == "343222931.0"].mcc.unique()

array([3501, 3533, 8099, 7011], dtype=int64)

In [97]:
mcc_mapped.to_csv("mcc_mapped.csv")

In [100]:
combined_csv_Siren_Cleaned.serial_number.unique()

array(['401153046', 'CT81286581', 'WL82159494', ..., '313933305',
       'WL11100708', 'PT62550094'], dtype=object)

In [103]:
mcc_mapped.application.isna().value_counts()

False    6853425
True       17486
Name: application, dtype: int64

In [104]:
mcc_mapped.application.nunique()

15

In [106]:
Clean_SIREN_MCC_APPLICATION = mcc_mapped[mcc_mapped.application.notna()]

In [109]:
Clean_SIREN_MCC_APPLICATION[Clean_SIREN_MCC_APPLICATION["mcc"] == 5411].legal_infos_head_office_registration_number.unique()

array([7.53944636e+08, 8.44121723e+08, 8.24311468e+08, 8.33111164e+08,
       8.10420125e+08, 8.34258485e+08, 4.79174765e+08, 8.39208451e+08,
       4.38014276e+08, 3.15106237e+08, 5.72031649e+08, 4.99149557e+08,
       4.29240948e+08, 7.99228648e+08, 3.27237087e+08, 8.01686338e+08,
       5.30932565e+08, 3.26020799e+08, 3.30123514e+08, 4.21835505e+08,
       8.32996045e+08, 5.21229021e+08, 4.81738508e+08, 4.37500119e+08,
       8.31434568e+08, 5.12025586e+08, 8.23530043e+08, 8.39699923e+08,
       5.27673503e+08, 7.92762122e+08, 3.97511783e+08, 3.05931974e+08,
       3.30465287e+08, 5.25141305e+08, 8.34063679e+08, 3.00553864e+08,
       8.14100764e+08, 8.18379737e+08, 4.44884035e+08, 7.50065260e+08,
       8.03585793e+08, 8.29655117e+08, 8.42844664e+08, 4.11532385e+08,
       8.12815090e+08, 5.32001344e+08, 4.88811357e+08, 5.02734668e+08,
       4.43797022e+08, 8.43860446e+08, 8.11834449e+08, 5.24373537e+08,
       4.40753101e+08, 3.89795519e+08, 8.18507410e+08, 7.99808910e+08,
       3.26739224e+08, 8.31204391e+08, 5.31504645e+08, 8.13693504e+08,
       3.14036179e+08, 8.30829420e+08, 5.62122127e+08, 5.00691399e+08,
       4.50984232e+08, 5.12726076e+08, 5.07949584e+08, 7.99602891e+08,
       8.43668971e+08, 8.40746366e+08, 5.02556301e+08, 8.12734887e+08,
       5.21315382e+08, 3.20595861e+08, 5.25023362e+08, 3.52858229e+08,
       8.07625165e+08, 8.38417517e+08, 5.24478039e+08, 8.00676231e+08,
       7.12030931e+08, 8.32131809e+08, 8.19967472e+08, 4.21820986e+08,
       8.31563051e+08, 8.32939441e+08, 3.25554566e+08, 4.38068892e+08,
       8.27934886e+08, 5.12018615e+08, 8.29343490e+08, 8.43794348e+08,
       8.09385719e+08, 7.95116672e+08, 7.50574543e+08, 8.14108171e+08,
       5.38425158e+08, 7.53221704e+08, 4.34565974e+08, 8.10397539e+08,
       7.88768463e+08, 3.37725790e+08, 4.93138259e+08, 4.34739892e+08,
       8.13200128e+08, 8.39918091e+08, 8.13061116e+08, 5.35393086e+08,
       4.93781173e+08, 3.90733012e+08, 4.92005830e+08, 4.80177104e+08,
       3.38620859e+08, 7.97511755e+08, 8.14945077e+08, 8.34876781e+08,
       8.11913177e+08, 5.22732403e+08, 5.32667144e+08, 8.44092593e+08,
       5.24302833e+08, 8.35050105e+08, 4.02969018e+08, 3.34488376e+08,
       3.05207912e+08, 8.12475564e+08, 8.29911064e+08, 8.12364198e+08,
       4.84101761e+08, 5.11067647e+08, 7.53103308e+08, 8.11856939e+08,
       4.91836342e+08, 7.97725520e+08, 5.91031927e+08, 8.34546673e+08,
       8.19142019e+08, 8.03703990e+08, 5.05326454e+08, 8.33407679e+08,
       8.12032803e+08, 3.99897891e+08, 4.83510756e+08, 8.24823108e+08,
       5.33298543e+08, 8.25241318e+08, 4.49542349e+08, 8.19257312e+08,
       3.79162977e+08, 8.29623602e+08, 4.10620314e+08, 4.51612832e+08,
       8.01178641e+08, 3.79371933e+08, 5.11838492e+08, 7.99383229e+08,
       4.19767140e+08, 3.01762548e+08, 8.22037131e+08, 4.77693923e+08,
       8.31119839e+08, 5.30308576e+08, 5.28985302e+08, 3.39752636e+08,
       5.14009059e+08, 5.30304179e+08, 3.78255202e+08, 8.44409649e+08,
       8.43529520e+08, 5.28411515e+08, 8.28839217e+08, 4.32443778e+08,
       8.18813008e+08, 5.12084476e+08, 3.13966517e+08, 8.31250881e+08,
       8.18486680e+08, 5.29551699e+08, 4.94133879e+08, 8.33745342e+08,
       4.48971242e+08, 8.14231148e+08, 4.13955915e+08, 8.40894364e+08,
       8.18618720e+08, 3.38785967e+08, 8.18250474e+08, 7.94895896e+08,
       3.30109919e+08, 8.32389126e+08, 8.23509252e+08, 5.24644655e+08,
       8.09103294e+08, 8.14860870e+08, 8.42267031e+08, 8.04224632e+08,
       4.39416124e+08, 4.07562966e+08, 5.25247011e+08, 3.85209200e+08,
       4.53200594e+08, 4.79767162e+08, 4.80709419e+08, 4.98009315e+08,
       4.38134959e+08, 8.17766546e+08, 4.94569353e+08, 8.01394115e+08,
       8.30870101e+08, 8.02070334e+08, 8.11692391e+08, 7.95278555e+08,
       7.98500948e+08, 8.13687423e+08, 5.34448972e+08, 4.17967130e+08,
       7.99160957e+08, 8.41564412e+08, 8.42018657e+08, 8.21871183e+08,
       3.22105693e+08, 4.04152928e+08, 5.10935307e+08, 8.31374707e+08,
       8.15275250e+08, 8.19652496e+08, 4.90177276e+08, 4.19515127e+08,
       4.81114015e+08, 5.04616418e+08, 8.42392151e+08, 8.31567060e+08,
       3.33340339e+08, 8.40389480e+08, 4.11815392e+08, 8.21052768e+08,
       4.40828416e+08, 4.48985614e+08, 4.99691137e+08, 8.11134030e+08,
       8.10919407e+08, 9.41370980e+07, 7.99584859e+08, 8.07478995e+08,
       8.22418729e+08, 7.94719641e+08, 8.31821491e+08, 8.24459028e+08,
       8.10743286e+08, 7.90040026e+08, 5.07678332e+08, 5.01566798e+08,
       5.39944199e+08, 7.52912956e+08, 4.41403672e+08, 8.39602141e+08,
       8.27503988e+08, 5.38351172e+08, 8.38042943e+08, 8.04942126e+08,
       5.01224729e+08, 8.39877578e+08, 8.04499887e+08, 8.38505055e+08,
       4.91357604e+08, 5.14775485e+08, 8.28069146e+08, 5.13501338e+08,
       5.19976690e+08, 4.94359086e+08, 4.91858049e+08, 3.32308386e+08,
       5.21418228e+08, 4.24780146e+08, 7.90370985e+08, 8.24988802e+08,
       8.29742097e+08, 5.28152937e+08, 3.82500429e+08, 7.90270938e+08,
       8.25049356e+08, 5.05106906e+08, 8.42892556e+08, 8.33529910e+08,
       8.21721388e+08, 8.41159569e+08, 7.94614628e+08, 5.00965355e+08,
       3.52297543e+08, 8.09141666e+08, 5.22271287e+08, 8.08548754e+08,
       4.99294957e+08, 8.38022812e+08, 4.11117112e+08, 4.49782408e+08,
       3.38974058e+08, 8.35237280e+08, 3.83316510e+08, 4.93947469e+08,
       7.99138979e+08, 8.32950083e+08, 8.12834786e+08, 5.21845115e+08,
       8.08762694e+08, 3.32167436e+08, 8.15089529e+08, 4.82327137e+08,
       4.34657219e+08, 5.19156566e+08, 4.89048728e+08, 3.94699375e+08,
       5.27604458e+08, 5.17871547e+08, 8.23117189e+08, 7.51038860e+08,
       8.08381578e+08, 8.02502781e+08, 8.03149442e+08, 8.04625606e+08,
       8.20262756e+08, 5.18667845e+08, 4.13827957e+08, 4.39318023e+08,
       3.78690358e+08, 8.28110874e+08, 3.77717707e+08, 8.20578367e+08,
       8.44408617e+08, 8.21354875e+08, 3.29600563e+08, 7.93757709e+08,
       4.24582377e+08, 8.28680827e+08, 8.24427884e+08, 4.18692232e+08,
       7.92759110e+08, 4.43084967e+08, 5.03024259e+08, 5.22804020e+08,
       8.43619156e+08, 8.13194495e+08, 5.21172056e+08, 8.34322869e+08,
       6.11780404e+08, 8.32007538e+08, 3.50641825e+08, 8.29546555e+08,
       8.05058914e+08, 8.44840009e+08, 8.22790168e+08, 3.08065499e+08,
       4.88357120e+08, 8.10175265e+08, 5.82113320e+08, 8.02820191e+08,
       5.21243626e+08, 3.99028950e+08, 4.94898455e+08, 5.23277424e+08,
       3.47666984e+08, 4.88591744e+08, 4.85086250e+08, 8.29456631e+08,
       4.20788036e+08, 7.92769648e+08, 8.20581759e+08, 3.85122296e+08,
       8.23255773e+08, 4.08834679e+08, 5.35156244e+08, 8.30381588e+08,
       5.09169165e+08, 5.30188002e+08, 3.79859622e+08, 8.12070381e+08,
       8.07703939e+08, 3.42276177e+08, 3.82070225e+08, 4.24344182e+08,
       8.42828261e+08, 3.79406481e+08, 7.88952349e+08, 4.88176181e+08,
       4.94319544e+08, 4.20840092e+08, 3.33403202e+08, 8.31117056e+08,
       5.33089199e+08, 3.83772886e+08, 8.30764130e+08, 5.30658186e+08,
       7.53329671e+08, 8.00879827e+08, 8.39308442e+08, 5.14828193e+08,
       3.78507149e+08, 8.13892569e+08, 8.04313336e+08, 7.90022669e+08,
       5.19650097e+08, 8.41719925e+08, 5.24033586e+08, 8.24837702e+08,
       8.41128150e+08, 8.10257691e+08, 8.38546067e+08, 8.31962733e+08,
       8.20711265e+08, 3.85025747e+08, 8.24633820e+08, 3.78808760e+08,
       8.22679809e+08, 8.23564422e+08, 5.00924436e+08, 7.98425518e+08,
       8.37637503e+08, 4.92471016e+08, 8.10907295e+08, 8.02714295e+08,
       5.31506798e+08, 8.39054723e+08, 8.39488624e+08, 3.14491929e+08,
       4.23980408e+08, 5.29047797e+08, 4.07545383e+08, 8.38446060e+08,
       8.44221952e+08, 5.02419732e+08, 8.31545066e+08, 4.10509806e+08,
       5.02178858e+08, 3.48292475e+08, 7.99492277e+08, 3.31282962e+08,
       5.14040435e+08, 3.88552069e+08, 3.83475316e+08, 4.37671688e+08,
       4.80124197e+08, 8.28421461e+08, 8.08499818e+08, 8.41047525e+08,
       3.30157678e+08, 4.84955307e+08, 8.43245192e+08, 4.78297914e+08,
       8.19694191e+08, 8.15260450e+08, 5.30261783e+08, 8.31452255e+08,
       3.32358548e+08, 3.41087799e+08, 3.82479673e+08, 3.91752771e+08,
       7.91322969e+08, 3.90795912e+08, 4.93584312e+08, 8.08716419e+08,
       5.00236211e+08, 7.95330877e+08, 8.18808016e+08, 7.53536572e+08,
       7.92913089e+08, 8.19466061e+08, 5.23900363e+08, 3.32908854e+08,
       8.44479964e+08, 4.51046775e+08, 8.42077448e+08, 8.43314923e+08,
       8.40562300e+08, 8.22260832e+08, 8.43281544e+08, 4.82678836e+08,
       5.32121589e+08, 5.35141659e+08, 4.82816626e+08, 5.08888849e+08,
       8.17861719e+08, 4.32456713e+08, 8.02614271e+08, 7.99679774e+08,
       7.90220164e+08, 4.99932176e+08, 5.07701563e+08, 8.23287420e+08,
       8.02284570e+08, 8.12876472e+08, 3.94798987e+08, 4.31745736e+08,
       4.79461360e+08, 8.11020973e+08, 3.19292710e+08, 4.91792677e+08,
       3.77080221e+08, 5.14988849e+08, 8.03286046e+08, 4.01958111e+08,
       3.33418606e+08, 4.01819511e+08, 8.03065168e+08, 3.25782043e+08,
       8.33520489e+08, 4.89139584e+08, 4.84784467e+08, 8.44255646e+08,
       5.39439166e+08, 3.12562515e+08, 3.34345576e+08, 8.24458426e+08,
       3.90129849e+08, 6.52028648e+08, 3.47563124e+08, 8.31193222e+08,
       8.11883867e+08, 8.40619498e+08, 5.21559609e+08, 8.31407804e+08,
       8.09644792e+08, 8.32489561e+08, 5.01219323e+08, 8.22480042e+08,
       4.88621608e+08, 8.41277734e+08, 4.88346750e+08, 3.52359186e+08,
       8.42973505e+08, 4.19713698e+08, 7.52673897e+08, 5.34069737e+08,
       3.77969308e+08, 3.20685019e+08, 5.35135396e+08, 4.21374349e+08,
       3.94488753e+08, 8.13181195e+08, 4.02359947e+08, 4.00387783e+08,
       8.01244401e+08, 5.24834298e+08, 4.81019693e+08, 4.52338585e+08,
       3.79740319e+08, 8.08060974e+08, 8.19028366e+08, 3.24263714e+08,
       8.43936824e+08, 7.89623857e+08, 4.97588905e+08, 8.39142460e+08,
       4.44794341e+08, 4.84666508e+08, 8.11552116e+08, 3.27377099e+08,
       3.78685168e+08, 5.10404833e+08, 8.28768408e+08, 3.21319303e+08,
       5.34661350e+08, 8.42825655e+08, 4.03592934e+08, 8.41914518e+08,
       7.90684252e+08, 4.70200676e+08, 3.98441147e+08, 8.32910293e+08,
       4.91565693e+08, 4.93729321e+08, 4.87422552e+08, 4.34102067e+08,
       5.22249184e+08, 5.31507127e+08, 8.18561029e+08, 3.41941987e+08,
       8.34496960e+08, 8.12449619e+08, 8.44144857e+08, 5.10294556e+08,
       4.89893651e+08, 8.27986662e+08, 3.52941868e+08, 5.34044946e+08,
       5.23366219e+08, 3.51047626e+08, 3.43583464e+08, 8.32996359e+08,
       4.41088432e+08, 8.20461804e+08, 8.41715279e+08, 4.77915326e+08,
       7.94840280e+08, 4.44082747e+08, 7.50388035e+08, 5.05213066e+08,
       4.34178711e+08, 8.30499729e+08, 8.12431542e+08, 5.31401677e+08,
       5.14475805e+08, 3.01000196e+08, 8.17540412e+08, 4.84768486e+08,
       4.29450927e+08, 8.31962675e+08, 4.44864532e+08, 5.09290888e+08,
       5.92006555e+08, 4.50165972e+08, 4.98268366e+08, 5.18946900e+08,
       8.38041895e+08, 8.41676232e+08])

In [110]:
Clean_SIREN_MCC_APPLICATION.to_csv("Clean_SIREN_MCC_APPLICATION.csv", index=False, encoding='utf-8-sig')

In [111]:
Clean_SIREN_MCC_APPLICATION.mcc.nunique()

187

In [112]:
Clean_SIREN_MCC_APPLICATION.legal_infos_head_office_registration_number.nunique()

11818

In [113]:
Clean_SIREN_MCC_APPLICATION.serial_number.nunique()

16515

In [114]:
Clean_SIREN_MCC_APPLICATION.shape

(6853425, 42)

In [115]:
Clean_SIREN_MCC_APPLICATION.application.unique()

array(['CBEMV', 'CBCLESS', 'CONECS', 'CBVAD', 'PLBS+', 'CONECSCLESS',
       'PLBSGCB', 'AMEX', 'JCBEMV', 'DCCFCC', 'SOFINCO', 'PNFOZITO',
       'AMEXCLESS', 'POINTVERT', 'QUASI-CASH'], dtype=object)

In [119]:
applicationLists = Clean_SIREN_MCC_APPLICATION.application.unique()

In [122]:
for applicationList in applicationLists:
    Clean_SIREN_MCC_APPLICATION[applicationList] = np.where(Clean_SIREN_MCC_APPLICATION["application"] == applicationList,1,0)

<ipython-input-122-c1ba88c9d2f5>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Clean_SIREN_MCC_APPLICATION[applicationList] = np.where(Clean_SIREN_MCC_APPLICATION["application"] == applicationList,1,0)

In [125]:
Clean_SIREN_MCC_APPLICATION[Clean_SIREN_MCC_APPLICATION["CBCLESS"] == 1]

,created_at,serial_number,manufacturer,contract_number,contract_rank,bank_code,registration_number,legal_name,application,currency_code,mcc,local_transaction_datetime,credits_number,debits_number,debits_reversal_number,non_completed_number,credits_amount,debits_amount,debits_reversal_amount,transaction_count,local_transaction_datetime.1,amount,authorization_number,type,legal_infos_registration_number,legal_infos_head_office_registration_number,legal_infos_normalized_address_l7,legal_infos_postal_code,legal_infos_city_name,legal_infos_company_long_name,legal_infos_acronym,uniqueSIRENNumber,hasNaN,hasOnlyNaN,hasMoreThanOneSIRENExcludingNan,ToDiscard,UpdatedSIRENNumber,edited_description,combined_description,usda_description,irs_description,irs_reportable,CBEMV,CBCLESS,CONECS,CBVAD,PLBS+,CONECSCLESS,PLBSGCB,AMEX,JCBEMV,DCCFCC,SOFINCO,PNFOZITO,AMEXCLESS,POINTVERT,QUASI-CASH
24,2019-11-06 04:54:21.97653+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBCLESS,978,7991,2019-11-06 05:54:07,0,33,0,2,0.0,358.56,0.0,35,2019-11-05 13:12:40,4.10,442227,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Yes,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
25,2019-11-06 04:54:21.97653+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBCLESS,978,7991,2019-11-06 05:54:07,0,33,0,2,0.0,358.56,0.0,35,2019-11-05 13:15:22,12.90,067933,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Yes,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
26,2019-11-06 04:54:21.97653+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBCLESS,978,7991,2019-11-06 05:54:07,0,33,0,2,0.0,358.56,0.0,35,2019-11-05 13:16:22,15.65,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Yes,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
27,2019-11-06 04:54:21.97653+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBCLESS,978,7991,2019-11-06 05:54:07,0,33,0,2,0.0,358.56,0.0,35,2019-11-05 13:16:38,15.65,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Yes,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
28,2019-11-06 04:54:21.97653+00,401153046,VERIFONE,2930787,1,30002,8.400588e+13,BLOCK'OUT,CBCLESS,978,7991,2019-11-06 05:54:07,0,33,0,2,0.0,358.56,0.0,35,2019-11-05 13:17:59,4.20,NaN,DEBIT,8.400588e+13,840058762.0,FRANCE,69760.0,LIMONEST,BLOCK'OUT,NaN,840058762.0,False,False,False,False,nan,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Tourist Attractions and Exhibits,Yes,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6870785,2019-11-29 00:31:39.808591+00,CT60106936,SAGEM,3774514,801,30003,4.016121e+13,ARCADE CYCLES - ARCADE CYCLES,CBCLESS,978,5940,2019-11-29 01:30:17,0,3,0,0,0.0,36.10,0.0,3,2019-11-28 11:10:46,11.10,NaN,DEBIT,4.016121e+13,401612080.0,FRANCE,85000.0,LA ROCHE SUR YON,ARCADE CYCLES,NaN,401612080.0,False,False,False,False,nan,Bicycle Shops – Sales and Service,Bicycle Shops – Sales and Service,Bicycle Shops – Sales and Service,Bicycle Shops,No1.6041-3(c),0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
6870786,2019-11-29 00:31:39.808591+00,CT60106936,SAGEM,3774514,801,30003,4.016121e+13,ARCADE CYCLES - ARCADE CYCLES,CBCLESS,978,5940,2019-11-29 01:30:17,0,3,0,0,0.0,36.10,0.0,3,2019-11-28 16:23:13,14.50,NaN,DEBIT,4.016121e+13,401612080.0,FRANCE,85000.0,LA ROCHE SUR YON,ARCADE CYCLES,NaN,401612080.0,False,False,False,False,nan,Bicycle Shops – Sales and Service,Bicycle Shops – Sales and Service,Bicycle Shops – Sales and Service,Bicycle Shops,No1.6041-3(c),0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
6870787,2019-11-29 00:31:39.808591+00,CT60106936,SAGEM,3774514,801,30003,4.016121e+13,ARCADE CYCLES - ARCADE CYCLES,CBCLESS,978,5940,2019-11-29 01:30:17,0,3,0,0,0.0,36.10,0.0,3,2019-11-28 14:42:14,10.50,NaN,DEBIT,4.016121e+13,401612080.0,FRANCE,85000.0,LA ROCHE SUR YON,ARCADE CYCLES,NaN,401612080.0,False,False,False,False,nan,Bicycle Shops – Sales and Service,Bicycle Shops – Sales and Service,Bicycle Shops – Sales and Service,Bicycle Shops,No1.6041-3(c),0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
6870788,2019-11-30 00:32:38.781972+00,CT60106936,SAGEM,3774514,801,30003,4.016121e+13,ARCADE CYCLES - ARCADE CYCLES,CBCLESS,978,5940,2019-11-30 01:31:02,0,2,0,0,0.0,20.80,0.0,2,2019-11-29 12:11:52,15.60,210874,DEBIT,4.016121e+13,401612080.0,FRANCE,85000.0,LA ROCHE SUR YON,ARCADE CYCLES,NaN,401612080.0,False,False,False,False,nan,Bicycle Shops – Sales and Service,Bicycle Shops – Sales and Service,Bicycle Shops – Sales and Service,Bicycle Shops,No1.6041-3(c),0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
6870789,2019-11-30 00:32:38.781972+00,CT60106936,SAGEM,3774514,801,30003,4.016121e+13,ARCADE CYCLES - ARCADE CYCLES,CBCLESS,978,5940,2019-11-30 01:31:02,0,2,0,0,0.0,20.80,0.0,2,2019-11-29 14:18:57,5.20,NaN,DEBIT,4.016121e+13,401612080.0,FRANCE,85000.0,LA ROCHE SUR YON,ARCADE CYCLES,NaN,401612080.0,False,False,False,False,nan,Bicycle Shops – Sales and Service,Bicycle Shops – Sales and Service,Bicycle Shops – Sales and Service,Bicycle Shops,No1.6041-3(c),0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [135]:
CurrencyCodes = Clean_SIREN_MCC_APPLICATION.currency_code.unique()

In [136]:
for currencyCode in CurrencyCodes:
    print("Currency,",currencyCode,":",Clean_SIREN_MCC_APPLICATION[Clean_SIREN_MCC_APPLICATION.currency_code == currencyCode].shape[0])

Currency, 978 : 6852547
Currency, 356 : 1
Currency, 826 : 21
Currency, 756 : 651
Currency, 840 : 176
Currency, 124 : 2
Currency, 392 : 4
Currency, 484 : 3
Currency, 414 : 1
Currency, 784 : 15
Currency, 36 : 3
Currency, 702 : 1

In [138]:
Clean_SIREN_MCC_APPLICATION.application.nunique()

15